# Generated by Django 5.1.7 on 2025-04-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariods16',
            old_name='edv',
            new_name='animais',
        ),
        migrations.RenameField(
            model_name='usuariods16',
            old_name='apelido',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='usuariods16',
            old_name='padrinho',
            new_name='escolaridade',
        ),
        migrations.RemoveField(
            model_name='usuariods16',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='biografia',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='idade',
            field=models.PositiveIntegerField(default=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariods16',
            name='telefone',
            field=models.CharField(default='111919010', max_length=255),
            preserve_default=False,
        ),
    ]
