# Generated by Django 5.1.6 on 2025-02-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='A Fazer', max_length=100),
            preserve_default=False,
        ),
    ]
