# Generated by Django 5.1.7 on 2025-03-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_hora', models.DateTimeField()),
                ('local', models.TextField(blank=True, null=True)),
                ('categoria', models.TextField(blank=True, choices=[('MUSICA', 'Musica'), ('PALESTRA', 'Palestra'), ('WORKSHOP', 'Workshop')], null=True)),
            ],
        ),
    ]
